= MockWebServer for Junit 5

A scriptable web server for testing HTTP clients

This project is a fork of the project https://github.com/square/okhttp/tree/master/mockwebserver[okhttp-mockwebserver] (created by https://squareup.com/[Square]). This evolution targets any Java project with Java >=8 and with Juni t5. The rule `_MockWebServer_` is replaced by a Junit 5 extension `_MockWebServerExtension_`. This project exists because the initial one won't upgraded to Java 8 and Junit 5. 

This project is managed by Dev-Mind but you can send push request or open issues

== Motivation
This library makes it easy to test that your app Does The Right Thing when it makes HTTP and HTTPS calls. It lets you specify which responses to return and then verify that requests were made as expected.

Because it exercises your full HTTP stack, you can be confident that you're testing everything. You can even copy & paste HTTP responses from your real web server to create representative test cases. Or test that your code survives in awkward-to-reproduce situations like 500 errors or slow-loading responses.

=== Example
Use MockWebServerExtension the same way that you use other frameworks extensions like Spring:

  TODO


=== License
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.  
